update to spark 3.5.1 and rabbitmq client 5.21.0 scala test may have exceptions java.lang.NoClassDefFoundError: scala/Product$class as there is no amqp-client_2.12 version in maven